services:
  backend:
    build: ./Backend
    working_dir: /app
    environment:
      - UPLOAD_DIR=/app/uploads
      - CORS_ORIGINS=["http://localhost:3000"]
      - DETECTOR=auto
      - MODEL_WEIGHTS=yolov8n.pt
    volumes:
      - ./Backend/uploads:/app/uploads
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./Frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev -- --host"
